theme: jekyll-theme-cayman
title: International Thwaites Glacier Collaboration field and ship best practices 
description: Below is a fieldwork and ship best practises document initially created by the International Thwaites Glacier Collaboration's committee for Inclusion, Diversity, Equity and Antiracism.

This document is intended to be an ongoing collaborative effort across the polar science community.

All feedback and edits are welcome. To comment or suggest changes you can create an GitHub issue or you can make specific changes to index.md and submit them as a pull request.

Alternatively contact Jonny Kingslake (j.kingslake@columbia.edu) or the ITGC Science and Coordinateion Office (betsys@nsidc.org).